README.md
=> Update gstreamer link

README.md
- Adding an unit test library.
- Adding a packet crafting tool.
=> Add Cutest & pig

README.md
the `libpng` has appeared two times.
=> delete duplicate entry: libpng

README.md
Add a really popular IDE, which is often used for desktop or embedded c development
=> Add Editors: Qt Creator

README.md
Darknet is an open source neural network framework written in C and CUDA. It is fast, easy to install, and supports CPU and GPU computation.
http://pjreddie.com/darknet/
https://github.com/pjreddie/darknet
=> Add deep learning c library: Darknet

README.md
should not the libbson and libYAML be in the serialization section too?
=> Added binn serialization

README.md
Tried making a change and saw there was an auto build log that failed... now it passes!
=> Fixed Travis-ci build

README.md
There is a slew of randomly inserted licensing. Going off other popular Awesome repos I found that the best answer is first and for most one that is consistent across the entire repo. With needing a decision to go with, the format I choose was wrapping the license in `[ ]` at end of description and omit the period after it.
=> Refactoring of all licenses

README.md
Premake is truly awesome if you ask me
=> added Premake (Build Systems)

CONTRIBUTING.md
=> craete first draft of Contributing.md info

README.md
Useful library that I use pretty often.
=> Added utf8.h library

README.md
Stupid change on their part but meh, just want the awesome bot to stop complaining.
=> Fix qt features libraries 301 redirection

README.md
I can not find it on his github page anymore
=> Viola is no longer around

README.md
=> Fix SEI CERT C Coding Standard link

README.md
This is a library we've been working on, that simplifies the game networking architecture by providing a fast, simple modules that sync the game data in any networking topology desired.
=> Added librg

README.md
Found this recently. Looks interesting and a decent alternative to `libz`
=> Add libzip and Compression section

README.md
=> refactored to LIC for license links

CONTRIBUTING.md
=> updated Contributing for licenses

README.md
Not sure on the description (it is definitely biased) but I pulled it from their homepage.
After working with several projects and build systems, SCons has been a breath of fresh air.
=> Add SCons to Build Systems

README.md
This is a re-submit of PR #48 (too many merge conflicts)
=> Add language specs, rationale docs, and P99 lib

README.md
Greetings,
This list had some errors which I decided to fix. There were multiple entries out of place, a few duplicates, including uncategorized entries which clearly belonged in distinct categories. Thus I've created new categories, and appended important libraries/tools which seemed to be missing. Generally cleaned up the project. There are still some papers and educational resources missing, which I may add once I have the time. If the maintainers are interested I could add some one hundred or more, smaller, niche C libraries which I have cloned locally. Although, they are highly specific and not as generic as a list of this caliber may desire.
=> General overhaul and clean up

README.md
I did a thing. Here's an entry for the list.
=> add libvldmail

README.md
#62 
Wrote little Golang script to replace URLs, @aleksandar-todorovic merge if you give go ahead
=> Refactored links to be inline

README.md
added [genann](https://github.com/codeplea/genann)
=> added genann

README.md
Update check URL in the testing frameworks section.
=> Update Check url
